---
title: faker
url: ''
baseurl: ''
exclude:
- Rakefile
collections:
  apiarian_phantom:
    source: apiarian_phantom
    directory: apiarian_phantom
    layout: default
  fugas:
    source: fugas
    directory: fugas
    layout: default
  opinicus:
    source: opinicus
    directory: opinicus
    layout: default
lunr:
  content: false
  multi-language: true
  meta:
  - dir: apiarian_phantom
    fields:
    - pid
    - title
    - wyvern
    - ethereal
    - crone
    - rotfiend
    - therazane
    - grottore
  - dir: fugas
    fields:
    - pid
    - title
    - siren
    - hagubman
    - howler
    - shrieker
    - sylvan
    - dragon_of_fyresdal
  - dir: opinicus
    fields:
    - pid
    - title
    - leshen
    - harpy
    - doppler
    - slyzard_matriarch
    - endrega_warrior
    - erynias
