title: 'sample site'
url: ''
baseurl: ''
collections_dir: ''
source: ''
js:
  jquery:
    cdn: link
    version: version
collections:
  csv_collection:
    layout: default.html
    metadata:
      source: valid.csv
      labels: labels.yaml
    images:
      source: 'images/test_collection'
      iiif:
        label: gambrel
        description: indescribable
        attribution: blasphemous
        logo: '/path/to/logo'
  json_collection:
    layout: default.html
    metadata:
      source: valid.json
      labels: labels.yaml
    images:
      source: 'images/test_collection'
  yaml_collection:
    layout: default.html
    metadata:
      source: valid.yaml
      labels: labels.yaml
    images:
      source: 'images/test_collection'


lunr:
  index:
    - collections: ['csv_collection', 'json_collection', 'yaml_collection']
