title: 'sample site'
url: ''
baseurl: ''
collections_dir: ''
source: ''
js:
  jquery:
    cdn: link
    version: version
collections:
  test_collection:
    source: valid.csv
    layout: default.html
    keep_order: true
    lunr_index:
      content: true
      fields:
        - gambrel
        - indescribable
        - blasphemous
        - furtive
    iiif:
      variants: [100, 900]
