title: 'sample site'
url: ''
baseurl: ''
collections_dir: ''
source: ''
js:
  jquery:
    cdn: link
    version: version
collections:
  test_collection:
    layout: default.html
    metadata:
      source: valid.csv
      labels: labels.csv
    images:
      source: 'images/test_collection'
      iiif:
        label: gambrel
        description: indescribable
        attribution: blasphemous
        logo: '/path/to/logo'


lunr:
  index:
    - collections: ['test_collection']
