AllCops:
  Exclude:
    - 'spec/**/*'
Metrics/LineLength:
  Exclude:
    - 'lib/wax/utilities.rb'
    - 'lib/wax/index.rb'
Metrics/BlockLength:
  Exclude:
    - 'lib/wax/tasks/*'
Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Max: 20
