AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'spec/**/*'
Metrics/LineLength:
  IgnoredPatterns:
    - 'raise'
    - 'puts'
    - 'ÈÉÊË'
    - 'EEEE'
Style/FrozenStringLiteralComment:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Metrics/AbcSize:
  Max: 20
