AllCops:
  TargetRubyVersion: 2.5
  Exclude: ['spec/**/*', 'test_build/**/*']
Metrics/LineLength:
  IgnoredPatterns: ['raise', 'puts', 'set', 'warn', 'ÈÉÊË', 'EEEE', 'safe_join', 'spec']
Metrics/AbcSize:
  Max: 26
Metrics/MethodLength:
  Max: 15
Layout/EmptyComment:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
