## Metrics
Metrics/AbcSize:
  Max: 50
Metrics/MethodLength:
  Max: 30
Metrics/LineLength:
  Enabled: false

## Style
Style/GlobalVars:
  AllowedVariables: ['$config', '$argv', '$collection_data']
Style/HashSyntax:
  EnforcedStyle: no_mixed_keys
Style/MixinUsage:
  Enabled: false
Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true
Style/StringLiterals:
  Enabled: false
Style/Next:
  Enabled: false
