AllCops:
  TargetRubyVersion: 2.4
  Exclude: ['spec/**/*', 'test_build/**/*']
Metrics/LineLength:
  IgnoredPatterns: ['raise', 'puts', 'set', 'warn', 'ÈÉÊË', 'EEEE', 'safe_join']
Metrics/AbcSize:
  Max: 21
Metrics/MethodLength:
  Max: 13
Layout/EmptyComment:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
# Metrics/ClassLength:
#   Enabled: false
