## Metrics
Metrics/AbcSize:
  Max: 40
Metrics/MethodLength:
  Max: 40
Metrics/LineLength:
  Enabled: false
Metrics/BlockLength:
  Max: 40

## Style
Style/HashSyntax:
  EnforcedStyle: no_mixed_keys
Style/MixinUsage:
  Enabled: false
Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true
Style/StringLiterals:
  Enabled: false
Style/Next:
  Enabled: false
