AllCops:
  TargetRubyVersion: 2.4
  Exclude: ['spec/**/*']
Metrics/LineLength:
  IgnoredPatterns: ['raise', 'puts', 'ÈÉÊË', 'EEEE', 'make_path']
Style/FrozenStringLiteralComment:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Metrics/AbcSize:
  Max: 20
Metrics/MethodLength:
  Max: 15
Style/DoubleNegation:
  Enabled: false
Style/GuardClause:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Lint/NonLocalExitFromIterator:
  Enabled: false
