AllCops:
  TargetRubyVersion: 2.4
  Exclude: ['spec/**/*', 'test_build/**/*']
Metrics/LineLength:
  IgnoredPatterns: ['raise', 'puts', '\A#', 'root_path', 'ÈÉÊË', 'EEEE']
Style/RedundantSelf:
  Enabled: false
Metrics/AbcSize:
  Max: 25
Metrics/MethodLength:
  Max: 17
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyComment:
  Enabled: false
