AllCops:
  TargetRubyVersion: 2.4
  Exclude: ['spec/**/*']
Metrics/LineLength:
  IgnoredPatterns:
    - 'raise'
    - 'puts'
    - '\A#'
    - 'root_path'
    - 'ÈÉÊË'
    - 'EEEE'
Style/RedundantSelf:
  Enabled: false
Metrics/AbcSize:
  Max: 40
Metrics/MethodLength:
  Max: 30
Style/DoubleNegation:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/AlignHash:
  Enabled: false
