AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'spec/**/*'
Metrics/LineLength:
  IgnoredPatterns:
    - 'raise'
    - 'puts'
    - 'ÈÉÊË'
    - 'EEEE'
Style/FrozenStringLiteralComment:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Metrics/AbcSize:
  Max: 20
Metrics/MethodLength:
  Max: 15
Style/DoubleNegation:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
