AllCops:
  TargetRubyVersion: 2.4
  Exclude: ['spec/**/*']
Metrics/LineLength:
  IgnoredPatterns:
    - 'raise'
    - 'puts'
    - 'ÈÉÊË'
    - 'EEEE'
    - 'make_path'
    - 'gem'
Style/FrozenStringLiteralComment:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Metrics/AbcSize:
  Max: 22
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/MethodLength:
  Max: 20
Style/DoubleNegation:
  Enabled: false
Style/GuardClause:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
