## Metrics
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/ParameterLists:
  Max: 8
Metrics/AbcSize:
  Max: 40
Metrics/MethodLength:
  Max: 40
Metrics/BlockLength:
  Max: 40
Metrics/LineLength:
  Exclude:
    - 'lib/modules/lunr.rb'

## Style
Style/HashSyntax:
  Exclude:
    - 'lib/tasks/*'
Style/Next:
  Enabled: false

## Naming
Naming/UncommunicativeMethodParamName:
  Enabled: false
