sudo: true
language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
addons:
  apt:
    packages:
      - ghostscript
      - tree
env:
  global:
    - CC_TEST_REPORTER_ID=4bff8432781049a5d67ff0f07ced7b5fc248ec37f1624b54d14daa5807b55eaf
before_install:
  - gem update --system
  - gem install bundler
  - sudo rm /etc/ImageMagick-6/policy.xml
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rubocop
  - DEBUG=true bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
