language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
script:
  - bundle exec rubocop
  - bundle exec rspec
branches:
  only:
    - master
after_success:
  - bundle exec rake wax:push:s3
  - bundle exec rake wax:push:gh
