title: ""
description:""
baseurl: ""
url: ""

# Build settings
markdown: kramdown

exclude: [Gemfile*, node_modules, vendor]

collections:
  test_collection:
    output: true
    source: test_collection.csv
    key: id
    directory: test
    layout: test-page
  test_collection2:
    output: true
    source: test_collection2.yaml
    key: id
    directory: test2
    layout: test-page-special

webrick:
  headers:
    "Access-Control-Allow-Origin": "*"
