title: faker
url: ''
baseurl: ''

lunr_language: true
collections:
  abaya:
    source: abaya
    directory: abaya
    layout: default
    lunr_index:
      content: false
      display_field: title
      fields: [grottore, shaelmaar, royal_wyvern, ignis_fatuus, harpy]
  fire_elemental:
    source: fire_elemental
    directory: fire_elemental
    layout: default
    lunr_index:
      content: false
      display_field: title
      fields: [ekhidnae, giant_centipede, crone, cyclopse, hym]
